export const ActionTypes = {
  FETCH_BOOKS: "FETCH_BOOKS",
  FETCH_SEARCH_BOOKS: "FETCH_SEARCH_BOOKS",
  FETCH_CART: "FETCH_CART",
  ADD_TO_CART: "ADD_TO_CART",
  UPDATE_CART: "UPDATE_CART",
  DELETE_FROM_CART: "DELETE_FROM_CART",
};
